### ISSUE TITLE
Memory issue for adding large number of records.

### ISSUE THREAD

**Issue by sonalk** [litehelpers/Cordova-sqlite-storage#18]
hi,
i m aiming to use this plugin to store around 40 tables with 40000 records in each table but my it doesnt store records more than 70000 for a single table and not more than 40000 for 2 tables. i think there is some memory issue.
i also tried increasing the memory using 
SQLiteDatabase mydb = SQLiteDatabase.openOrCreateDatabase(dbfile, null);	mydb.setMaximumSize(300*1024*1024);
but still the same problem.
Also i wanted to know where are these tables stored on the phone.
Hoping to get a response very soon.
Thanks, 
Sonal

**Comment by brody2consult** [comment]
This limitation is now documented in README.md.

**Comment by scottjpearson** [comment]
Is there any way that you could specify in more detail what you see to be the problem in the JavaScript? We have a large international project hanging on this. I'm not asking you to fix it. I'd like to see if I can fix it for you. I've got the go-ahead to devote some time to it.

**Comment by brody2consult** [comment]
> Is there any way that you could specify in more detail what you see to be
> the problem in the JavaScript?

If you try to run the test program on Android, the Java code will crash
with an exception that memory cannot be allocated. I looked at this 1-2
years ago. The exception stack trace will show you that you run out of
memory while decoding JSON.

**Comment by scottjpearson** [comment]
Thanks.

Scott J. Pearson
REDCap Core Programmer, Project REDCap
REDCap Mobile App
http://projectredcap.org
Vanderbilt Institute for Clinical and Translational Research (VICTR)
615-322-6039 (o)

**Comment by brody2consult** [comment]
Reopening as a bug, hoping to find a solution. Will add an automatic test case for this.

UPDATE: This is caused by the JSON framework that is used in the Cordova project itself. I will make an isolated test scenario for Cordova (without this plugin) and raise a bug report when I get a chance.

**Comment by reconka** [comment]
Of course  its super slow  the insertion, if you are inserting 2 values in  one   executeSQL,
My application also working with  huge dataset.. Here is my test:
tx.executeSql    1 insert     84k row     6.4sec
tx.executeSql    10 insert (bulk)    84k row  1.6 sec
tx.executeSql    100 insert (bulk)    84k row  1.3 sec

I also noticed  the select can be  really slow if I am using  Join in my query. My workaround   was simple (and silly ), I  created a table, and inserted the result of the  join, so I  don't have to use multiple joins.

**Comment by reconka** [comment]
Here is my   simple example  https://gist.github.com/reconka/370b8aeb21215dbbd712 , please   paste into chrome/safari web developer console and  change the  limitation variable 
1 row/executeSQL :  35ms
100 row/executeSQL: 18ms

**Comment by brody2consult** [comment]
@rekona your problem has nothing to do with this issue. This issue is specifically about a crash that happens on the Android version _only_, which happens when the Java side of the Cordova framework attempts to decode the JSON message before calling the `execute()` method on this plugin. Your issue _may_ be related to #288 but I cannot say for sure. I recommend that you raise a new issue, and also specify which in platform(s) you see the problem.

**Comment by brody2consult** [comment]
I have added a test based on the reproduction test program by @sonalk to the `cordova-sqlite-common` branch, and have made a partial test fix here: https://github.com/brodybits/Cordova-sqlite-storage-dev/tree/cb-android-json-fix-1

It fixes the JSON problem in the Javascript --> Android Java direction by sending the data as a flat array instead of an array of Javascript/JSON objects. I was able to pass the rest of the test suite that is in the `cordova-sqlite-common` branch. However, when running the reproduction test program, it now runs into the memory issue when assembling the JSON response data. I will try to solve this part in the next few days or so.

**Comment by brody2consult** [comment]
I just submitted https://issues.apache.org/jira/browse/CB-9353 to report this issue on the Apache Cordova project.

**Comment by brody2consult** [comment]
Solution is now given in https://github.com/litehelpers/Cordova-sqlite-enterprise-free under GPL or purchased commercial license options.

**Comment by Samaludheen** [comment]
Hi Brodybits,
If I insert large data (appx. 40 MB base64 string) will it cause any problem?

**Comment by ravi04bit** [comment]
Hi Brodybits, 

Is there a trail version for the 'Cordova-sqlite-enterprise-free ' plugin to try out if it really fixes my out of memory issue and then purchase the licensed version?

Thanks,
Ravi Kumar M
