### ISSUE TITLE
Firefox OS support

### ISSUE THREAD

**Issue by luigi37** [litehelpers/Cordova-sqlite-storage#224]
Hi, is there any plan to take this plugin to Firefoxos? Thanks!

**Comment by brodybits** [comment]
Thanks for the inquiry, added to the queue.

**Comment by luigi37** [comment]
Hi, any progress here? Happy to beta test if needed... Thanks!

**Comment by nolanlawson** [comment]
Firefox OS support would require a shim for WebSQL over IndexedDB, since Mozilla has taken the position that they will never support WebSQL nor allow access to SQLite (even though they use it under the hood for IndexedDB).

@agershun and I had some ideas to build such a thing, but I admit I lost interest. He put some effort into the SQL parser, though: https://github.com/agershun/WebSQLShim

**Comment by nolanlawson** [comment]
Alternatively you could use [SQL.js](https://github.com/kripken/sql.js), but it does not persist to disk.

**Comment by luigi37** [comment]
Yes, really a shame Firefox OS does not support WebSQL. SQL.js looks promising... I'm unsure about the persistency issue... Thanks. I will give those two a look.
